//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework.Common.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homework.Common.Web.Resources.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all.
        /// </summary>
        internal static string btnDeleteAll {
            get {
                return ResourceManager.GetString("btnDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving data..
        /// </summary>
        internal static string error_OnSave {
            get {
                return ResourceManager.GetString("error.OnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System already contains requested user rights..
        /// </summary>
        internal static string error_UserRights_AlreadyExisting {
            get {
                return ResourceManager.GetString("error.UserRights.AlreadyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentials are not valid.
        /// </summary>
        internal static string ErrorCode_1001 {
            get {
                return ResourceManager.GetString("ErrorCode_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string ErrorCode_1002 {
            get {
                return ResourceManager.GetString("ErrorCode_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        internal static string ErrorCode_1004 {
            get {
                return ResourceManager.GetString("ErrorCode_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is locked.
        /// </summary>
        internal static string ErrorCode_1005 {
            get {
                return ResourceManager.GetString("ErrorCode_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string login_emailLbl {
            get {
                return ResourceManager.GetString("login.emailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must match regular expression &apos;^[\d\w._-]+@[\d\w._-]+\.[\w]+$&apos;.
        /// </summary>
        internal static string login_emailReqEx {
            get {
                return ResourceManager.GetString("login.emailReqEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required field.
        /// </summary>
        internal static string login_emailRequired {
            get {
                return ResourceManager.GetString("login.emailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string login_passwordLbl {
            get {
                return ResourceManager.GetString("login.passwordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required field.
        /// </summary>
        internal static string login_passwordRequired {
            get {
                return ResourceManager.GetString("login.passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string login_submitBtn {
            get {
                return ResourceManager.GetString("login.submitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login_title {
            get {
                return ResourceManager.GetString("login.title", resourceCulture);
            }
        }
    }
}
